export {
  analyzeBehavioralSamples,
  aggregateSuspicionScore,
  buildBehavioralSignals,
  createBehavioralClientDetector,
  hasClickWithoutMouseMovement,
  hasLinearMouseMovement,
  hasLinearScroll,
  hasLinearTyping,
  hasNoMouseActivity,
  hasSyntheticEvents,
  hasTeleportMouse,
  resolveConfidence,
} from "./behavioral/index.js";
export {
  checkShaderF16Support,
  default,
  detectInstantClient,
  detectInstantClientAsync,
  isAutomationArtifacts,
  isChromiumBrowser,
  isEmptyPlugins,
  isMissingChromeObject,
  isSoftwareRenderer,
  isSuspiciousWebDriverDescriptor,
  isSuspiciousWindowDimensions,
} from "./detectInstantClient.js";
export {
  aggregateServerSuspicionScore,
  buildServerSignals,
  createIpListChecker,
  detectServerClient,
  detectServerClientAsync,
  enrichServerContext,
  findTlsFingerprintEntry,
  getDefaultIpDataDir,
  getIpListChecker,
  getTimezoneOffsetMinutes,
  getUserAgentFamily,
  isAcceptLanguageGeoMismatch,
  isBrowserLikeUserAgent,
  isDatacenterBrowserMismatch,
  isKnownSuspiciousTlsFingerprint,
  isMissingTlsFingerprint,
  isTimezoneMismatch,
  isTlsUserAgentMismatch,
  KNOWN_SUSPICIOUS_TLS_FINGERPRINTS,
  lookupClientIpGeo,
  normalizeTlsFingerprint,
  resetIpListCheckerCache,
  resolveServerConfidence,
} from "./server/index.js";
export type {
  BehavioralClientDetector,
  BehavioralClientResult,
  BehavioralDetectorOptions,
  BehavioralSampleCounts,
  BehavioralSamples,
  BehavioralSignal,
  ConfidenceLevel,
} from "./behavioral/types.js";
export type {
  ServerClientContext,
  ServerClientResult,
  ServerConfidenceLevel,
  ServerDetectorOptions,
  ServerSignal,
  TlsFingerprintEntry,
  UserAgentFamily,
} from "./server/index.js";
export type {
  ExtendedDocument,
  ExtendedNavigator,
  ExtendedWindow,
  InstantClientAsyncResult,
  InstantClientResult,
} from "./types.js";
